@baseUrl = http://localhost:3333
@accessToken = {{authenticate.response.body.access_token}}
### 
# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "name": "John Doe",
  "password": "123456789"
}

### 
# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "leonardo@example.com",
  "password": "123456789"
}

### 
# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "example2",
  "content": "example2"
}

### 
# @name fetch_recent_questions
GET {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{accessToken}}
