@baseUrl = http://localhost:3333

### Create account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "email": "example@example.com",
  "name": "example",
  "password": "123456789"
}

### Authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "example@example.com",
  "password": "123456789"
}